name: 'Hackathon Action'
inputs:
  webhook_url: 
    description: "chat space url"
    type: 'string'
    required: true
  mention:
    description: "mention people or not, format <users/user_id>"
    type: 'string'
    default: '<users/all>'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'download binary'
      shell: 'bash'
      run: |-
        curl -LOv "https://github.com/drevell/hackathon/releases/download/v0.0.12/hackathon_0.0.12_linux_amd64.tar.gz"
        tar xzf hackathon_0.0.12_linux_amd64.tar.gz
    - name: "send message via cli"
      shell: 'bash'
      run: |
        ./hackathon chat workflownotification --webhook_url="${{ inputs.webhook_url }}"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        JOB_CONTEXT: ${{ toJson(job) }}
        STEPS_CONTEXT: ${{ toJson(steps) }}
        RUNNER_CONTEXT: ${{ toJson(runner) }}
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        MATRIX_CONTEXT: ${{ toJson(matrix) }}